// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qndoomkhcgcrselmocuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZG9vbWtoY2djcnNlbG1vY3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDQ1NzEsImV4cCI6MjA3NDQ4MDU3MX0.IwNZbd3NP5wtXjf4NbGgDo0lr8MN_zs8P-YY1nOqoW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});